sudo: required
os:
  - osx
  - linux
dist: trusty
language: cpp

env:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qt5-default libqt5x11extras5-dev qttools5-dev-tools ; fi

script:
    - mkdir build/
    - cd build/
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILDTYPE
    - make

compiler:
    - gcc
    - clang
