sudo: required
dist: xenial
language: cpp

env:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq qt59-meta-full libqt5x11extras5-dev

script:
    - source /opt/qt59/bin/qt59-env.sh
    - mkdir build/
    - cd build/
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILDTYPE
    - make

compiler:
    - gcc
    - clang
